# This file is autogenerated by hidl-gen. Do not edit manually.

LOCAL_PATH := $(call my-dir)

################################################################################

include $(CLEAR_VARS)
LOCAL_MODULE := vendor.volvocars.hardware.profiles-V1.0-java
LOCAL_MODULE_CLASS := JAVA_LIBRARIES

intermediates := $(call local-generated-sources-dir, COMMON)

HIDL := $(HOST_OUT_EXECUTABLES)/hidl-gen$(HOST_EXECUTABLE_SUFFIX)

LOCAL_JAVA_LIBRARIES := \
    android.hidl.base-V1.0-java \


#
# Build types.hal (KeyId)
#
GEN := $(intermediates)/vendor/volvocars/hardware/profiles/V1_0/KeyId.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.profiles@1.0::types.KeyId

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build types.hal (KeyLocation)
#
GEN := $(intermediates)/vendor/volvocars/hardware/profiles/V1_0/KeyLocation.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.profiles@1.0::types.KeyLocation

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build types.hal (KeyPairStatus)
#
GEN := $(intermediates)/vendor/volvocars/hardware/profiles/V1_0/KeyPairStatus.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.profiles@1.0::types.KeyPairStatus

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build types.hal (ProfileIdentifier)
#
GEN := $(intermediates)/vendor/volvocars/hardware/profiles/V1_0/ProfileIdentifier.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.profiles@1.0::types.ProfileIdentifier

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build ICarProfileManager.hal
#
GEN := $(intermediates)/vendor/volvocars/hardware/profiles/V1_0/ICarProfileManager.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/ICarProfileManager.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/IKeyPairResponseHandler.hal
$(GEN): $(LOCAL_PATH)/IKeyPairResponseHandler.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/IProfileChangedHandler.hal
$(GEN): $(LOCAL_PATH)/IProfileChangedHandler.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/types.hal
$(GEN): $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.profiles@1.0::ICarProfileManager

$(GEN): $(LOCAL_PATH)/ICarProfileManager.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build IKeyPairResponseHandler.hal
#
GEN := $(intermediates)/vendor/volvocars/hardware/profiles/V1_0/IKeyPairResponseHandler.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/IKeyPairResponseHandler.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/types.hal
$(GEN): $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.profiles@1.0::IKeyPairResponseHandler

$(GEN): $(LOCAL_PATH)/IKeyPairResponseHandler.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build IProfileChangedHandler.hal
#
GEN := $(intermediates)/vendor/volvocars/hardware/profiles/V1_0/IProfileChangedHandler.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/IProfileChangedHandler.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/types.hal
$(GEN): $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.profiles@1.0::IProfileChangedHandler

$(GEN): $(LOCAL_PATH)/IProfileChangedHandler.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)
include $(BUILD_JAVA_LIBRARY)


################################################################################

include $(CLEAR_VARS)
LOCAL_MODULE := vendor.volvocars.hardware.profiles-V1.0-java-static
LOCAL_MODULE_CLASS := JAVA_LIBRARIES

intermediates := $(call local-generated-sources-dir, COMMON)

HIDL := $(HOST_OUT_EXECUTABLES)/hidl-gen$(HOST_EXECUTABLE_SUFFIX)

LOCAL_STATIC_JAVA_LIBRARIES := \
    android.hidl.base-V1.0-java-static \


#
# Build types.hal (KeyId)
#
GEN := $(intermediates)/vendor/volvocars/hardware/profiles/V1_0/KeyId.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.profiles@1.0::types.KeyId

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build types.hal (KeyLocation)
#
GEN := $(intermediates)/vendor/volvocars/hardware/profiles/V1_0/KeyLocation.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.profiles@1.0::types.KeyLocation

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build types.hal (KeyPairStatus)
#
GEN := $(intermediates)/vendor/volvocars/hardware/profiles/V1_0/KeyPairStatus.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.profiles@1.0::types.KeyPairStatus

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build types.hal (ProfileIdentifier)
#
GEN := $(intermediates)/vendor/volvocars/hardware/profiles/V1_0/ProfileIdentifier.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.profiles@1.0::types.ProfileIdentifier

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build ICarProfileManager.hal
#
GEN := $(intermediates)/vendor/volvocars/hardware/profiles/V1_0/ICarProfileManager.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/ICarProfileManager.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/IKeyPairResponseHandler.hal
$(GEN): $(LOCAL_PATH)/IKeyPairResponseHandler.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/IProfileChangedHandler.hal
$(GEN): $(LOCAL_PATH)/IProfileChangedHandler.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/types.hal
$(GEN): $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.profiles@1.0::ICarProfileManager

$(GEN): $(LOCAL_PATH)/ICarProfileManager.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build IKeyPairResponseHandler.hal
#
GEN := $(intermediates)/vendor/volvocars/hardware/profiles/V1_0/IKeyPairResponseHandler.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/IKeyPairResponseHandler.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/types.hal
$(GEN): $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.profiles@1.0::IKeyPairResponseHandler

$(GEN): $(LOCAL_PATH)/IKeyPairResponseHandler.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build IProfileChangedHandler.hal
#
GEN := $(intermediates)/vendor/volvocars/hardware/profiles/V1_0/IProfileChangedHandler.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/IProfileChangedHandler.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/types.hal
$(GEN): $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.profiles@1.0::IProfileChangedHandler

$(GEN): $(LOCAL_PATH)/IProfileChangedHandler.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)
include $(BUILD_STATIC_JAVA_LIBRARY)



include $(call all-makefiles-under,$(LOCAL_PATH))
