/*
 * Copyright 2017 Volvo Car Corporation
 * This file is covered by LICENSE file in the root of this project
 */

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'iamgroot' at '5/30/17 8:31 PM' with Gradle 2.10
 *
 * @author iamgroot, @date 5/30/17 8:31 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
