# This file is autogenerated by hidl-gen. Do not edit manually.

LOCAL_PATH := $(call my-dir)

################################################################################

include $(CLEAR_VARS)
LOCAL_MODULE := vendor.volvocars.hardware.remotectrl-V1.0-java
LOCAL_MODULE_CLASS := JAVA_LIBRARIES

intermediates := $(call local-generated-sources-dir, COMMON)

HIDL := $(HOST_OUT_EXECUTABLES)/hidl-gen$(HOST_EXECUTABLE_SUFFIX)

LOCAL_JAVA_LIBRARIES := \
    android.hidl.base-V1.0-java \


#
# Build types.hal (AudioContext)
#
GEN := $(intermediates)/vendor/volvocars/hardware/remotectrl/V1_0/AudioContext.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.remotectrl@1.0::types.AudioContext

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build types.hal (StatusCode)
#
GEN := $(intermediates)/vendor/volvocars/hardware/remotectrl/V1_0/StatusCode.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.remotectrl@1.0::types.StatusCode

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build types.hal (VolumeData)
#
GEN := $(intermediates)/vendor/volvocars/hardware/remotectrl/V1_0/VolumeData.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.remotectrl@1.0::types.VolumeData

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build INativeRemoteAudioCtrl.hal
#
GEN := $(intermediates)/vendor/volvocars/hardware/remotectrl/V1_0/INativeRemoteAudioCtrl.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/INativeRemoteAudioCtrl.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/ISystemRemoteAudioCtrl.hal
$(GEN): $(LOCAL_PATH)/ISystemRemoteAudioCtrl.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/types.hal
$(GEN): $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.remotectrl@1.0::INativeRemoteAudioCtrl

$(GEN): $(LOCAL_PATH)/INativeRemoteAudioCtrl.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build ISystemRemoteAudioCtrl.hal
#
GEN := $(intermediates)/vendor/volvocars/hardware/remotectrl/V1_0/ISystemRemoteAudioCtrl.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/ISystemRemoteAudioCtrl.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/types.hal
$(GEN): $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.remotectrl@1.0::ISystemRemoteAudioCtrl

$(GEN): $(LOCAL_PATH)/ISystemRemoteAudioCtrl.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)
include $(BUILD_JAVA_LIBRARY)


################################################################################

include $(CLEAR_VARS)
LOCAL_MODULE := vendor.volvocars.hardware.remotectrl-V1.0-java-static
LOCAL_MODULE_CLASS := JAVA_LIBRARIES

intermediates := $(call local-generated-sources-dir, COMMON)

HIDL := $(HOST_OUT_EXECUTABLES)/hidl-gen$(HOST_EXECUTABLE_SUFFIX)

LOCAL_STATIC_JAVA_LIBRARIES := \
    android.hidl.base-V1.0-java-static \


#
# Build types.hal (AudioContext)
#
GEN := $(intermediates)/vendor/volvocars/hardware/remotectrl/V1_0/AudioContext.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.remotectrl@1.0::types.AudioContext

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build types.hal (StatusCode)
#
GEN := $(intermediates)/vendor/volvocars/hardware/remotectrl/V1_0/StatusCode.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.remotectrl@1.0::types.StatusCode

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build types.hal (VolumeData)
#
GEN := $(intermediates)/vendor/volvocars/hardware/remotectrl/V1_0/VolumeData.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.remotectrl@1.0::types.VolumeData

$(GEN): $(LOCAL_PATH)/types.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build INativeRemoteAudioCtrl.hal
#
GEN := $(intermediates)/vendor/volvocars/hardware/remotectrl/V1_0/INativeRemoteAudioCtrl.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/INativeRemoteAudioCtrl.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/ISystemRemoteAudioCtrl.hal
$(GEN): $(LOCAL_PATH)/ISystemRemoteAudioCtrl.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/types.hal
$(GEN): $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.remotectrl@1.0::INativeRemoteAudioCtrl

$(GEN): $(LOCAL_PATH)/INativeRemoteAudioCtrl.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build ISystemRemoteAudioCtrl.hal
#
GEN := $(intermediates)/vendor/volvocars/hardware/remotectrl/V1_0/ISystemRemoteAudioCtrl.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/ISystemRemoteAudioCtrl.hal
$(GEN): PRIVATE_DEPS += $(LOCAL_PATH)/types.hal
$(GEN): $(LOCAL_PATH)/types.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.volvocars.hardware:vendor/volvocars/interfaces \
        vendor.volvocars.hardware.remotectrl@1.0::ISystemRemoteAudioCtrl

$(GEN): $(LOCAL_PATH)/ISystemRemoteAudioCtrl.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)
include $(BUILD_STATIC_JAVA_LIBRARY)



include $(call all-makefiles-under,$(LOCAL_PATH))
