/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_ORG_VOLVOCARS_VOLVOONCALL_Volvo_On_Call_Backend_PROXY_BASE_HPP_
#define V0_ORG_VOLVOCARS_VOLVOONCALL_Volvo_On_Call_Backend_PROXY_BASE_HPP_

#include <v0/org/volvocars/VolvoOnCall/VolvoOnCallBackend.hpp>


#include <v0/org/volvo/connectivity/IpCommandBusTypes.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <cstdint>
#include <vector>

#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v0 {
namespace org {
namespace volvocars {
namespace VolvoOnCall {

class VolvoOnCallBackendProxyBase
    : virtual public CommonAPI::Proxy {
public:

    typedef std::function<void(const CommonAPI::CallStatus&, const ::v0::org::volvo::connectivity::IpCommandBusTypes::Infotainment_IP_bus_Errors&)> TextMessageSetRequestAsyncCallback;



    /**
     * description: (TextMessage 0x0106 SetRequest 0x02)
            This message is used for general
     *   text messages and received SMS from Customer Service Center, sent to TEM
     */
    virtual void TextMessageSetRequest(const ::v0::org::volvo::connectivity::IpCommandBusTypes::SourceStatus &_sourceStatus, const std::string &_source, const std::string &_text, CommonAPI::CallStatus &_internalCallStatus, ::v0::org::volvo::connectivity::IpCommandBusTypes::Infotainment_IP_bus_Errors &_error, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> TextMessageSetRequestAsync(const ::v0::org::volvo::connectivity::IpCommandBusTypes::SourceStatus &_sourceStatus, const std::string &_source, const std::string &_text, TextMessageSetRequestAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
};

} // namespace VolvoOnCall
} // namespace volvocars
} // namespace org
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_ORG_VOLVOCARS_VOLVOONCALL_Volvo_On_Call_Backend_PROXY_BASE_HPP_
